package launch

import (
	"github.com/spikeekips/mitum/base"
	"github.com/spikeekips/mitum/base/ballot"
	"github.com/spikeekips/mitum/base/block"
	"github.com/spikeekips/mitum/base/key"
	"github.com/spikeekips/mitum/base/operation"
	"github.com/spikeekips/mitum/base/state"
	"github.com/spikeekips/mitum/network"
	"github.com/spikeekips/mitum/util/hint"
	"github.com/spikeekips/mitum/util/tree"
)

var EncoderTypes = []hint.Type{
	ballot.ACCEPTFactType,
	ballot.ACCEPTType,
	ballot.INITFactType,
	ballot.INITType,
	ballot.ProposalFactType,
	ballot.ProposalType,
	ballot.SIGNFactType,
	ballot.SIGNType,
	base.BaseNodeV0Type,
	base.StringAddressType,
	base.VoteproofV0Type,
	base.BaseVoteproofNodeFactType,
	block.BaseBlockDataMapType,
	block.BlockConsensusInfoV0Type,
	block.BlockV0Type,
	block.ManifestV0Type,
	block.SuffrageInfoV0Type,
	key.BTCPrivatekeyType,
	key.BTCPublickeyType,
	key.EtherPrivatekeyType,
	key.EtherPublickeyType,
	key.StellarPrivatekeyType,
	key.StellarPublickeyType,
	network.NodeInfoType,
	network.ProblemType,
	operation.BaseFactSignType,
	operation.BaseReasonErrorType,
	operation.FixedTreeNodeType,
	operation.SealType,
	state.BytesValueType,
	state.DurationValueType,
	state.HintedValueType,
	state.NumberValueType,
	state.SliceValueType,
	state.StateV0Type,
	state.StringValueType,
	tree.BaseFixedTreeNodeType,
	tree.FixedTreeType,
}

var EncoderHinters = []hint.Hinter{
	ballot.ACCEPTFactV0{},
	ballot.ACCEPTV0{},
	ballot.INITFactV0{},
	ballot.INITV0{},
	ballot.ProposalFactV0{},
	ballot.ProposalV0{},
	ballot.SIGNFactV0{},
	ballot.SIGNV0{},
	base.BaseNodeV0{},
	base.StringAddress(""),
	base.VoteproofV0{},
	base.BaseVoteproofNodeFact{},
	block.BaseBlockDataMap{},
	block.BlockV0{},
	block.ConsensusInfoV0{},
	block.ManifestV0{},
	block.SuffrageInfoV0{},
	key.BTCPrivatekeyHinter,
	key.BTCPublickeyHinter,
	key.EtherPrivatekeyHinter,
	key.EtherPublickeyHinter,
	key.StellarPrivatekeyHinter,
	key.StellarPublickeyHinter,
	network.NodeInfoV0{},
	network.Problem{},
	operation.BaseFactSign{},
	operation.BaseReasonError{},
	operation.BaseSeal{},
	operation.FixedTreeNode{},
	state.BytesValue{},
	state.DurationValue{},
	state.HintedValue{},
	state.NumberValue{},
	state.SliceValue{},
	state.StateV0{},
	state.StringValue{},
	tree.BaseFixedTreeNode{},
	tree.FixedTree{},
}
